import os
import shutil
import zipfile

# Paths
base_dir = r"e:\3rd_year\hackthon"
source_dir = os.path.join(base_dir, "folder")
output_dir = os.path.join(base_dir, "Final_Gov_Submission")
zip_filename = os.path.join(base_dir, "Final_Submission_Aadhaar_Pulse.zip")

# Create Output Directory
if os.path.exists(output_dir):
    shutil.rmtree(output_dir)
os.makedirs(output_dir)

# Files to Copy
files_map = {
    "work.ipynb": "Solution_Notebook.ipynb",
    "README.md": "README.md",
    "Final_Comprehensive_Report.md": "Project_Report.md",
    "requirements.txt": "requirements.txt",
    "processed_district_data.csv": "Sample_Output_Data.csv"
}

print("Copying files...")
for original, new_name in files_map.items():
    src = os.path.join(base_dir, original) # Changed to base_dir as Report is in root now
    if original == "work.ipynb": src = os.path.join(source_dir, original) # Notebook is still in folder/
    
    dst = os.path.join(output_dir, new_name)
    if os.path.exists(src):
        shutil.copy2(src, dst)
        print(f"Copied {original} -> {new_name}")
    else:
        print(f"WARNING: {original} not found at {src}")

# Create Instructions File
instructions = """
Aadhaar Seva Pulse - Hackathon Submission
=========================================

Files Included:
1. Solution_Notebook.ipynb : The complete source code, analysis, and visualizations.
                             (Open this in Jupyter Notebook to verify).
2. Project_Report.md       : Comprehensive report of Methodology, Findings, and ML logic.
                             (Convert this to PDF if the portal requires PDF).
3. README.md               : Quick guide for the evaluators.
4. requirements.txt        : List of Python libraries used.
5. Sample_Output_Data.csv  : The final processed dataset generated by our code.

Note on Raw Data:
The raw datasets (Enrolment, Demographic, Biometric) are NOT included in this zip 
to keep the file size small (as per standard hackathon rules). 
The Notebook is designed to read the data from the standard paths provided in the challenge.
"""

with open(os.path.join(output_dir, "Instructions.txt"), "w", encoding="utf-8") as f:
    f.write(instructions)

print("Creating Zip Archive...")
with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files in os.walk(output_dir):
        for file in files:
            file_path = os.path.join(root, file)
            # Add file to zip with relative path
            arcname = os.path.relpath(file_path, base_dir) # Keep 'Final_Gov_Submission' folder structure in zip? 
            # Usually better to have the files flat or in a single folder. 
            # Let's put them inside a folder inside the zip
            arcname = os.path.relpath(file_path, base_dir)
            zipf.write(file_path, arcname)

print(f"Success! Created {zip_filename}")
